#!/usr/bin/env python3
"""
Daily Tasks Scheduler for Silver Tier
Creates daily summary tasks and recurring task reminders
"""

import logging
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('daily_tasks')


class DailyTasksScheduler:
    """
    Daily tasks scheduler that creates recurring tasks and daily summaries.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the Daily Tasks Scheduler.
        
        Args:
            vault_path: Path to AI_Employee_Vault directory
        """
        self.vault_path = Path(vault_path)
        self.inbox_folder = self.vault_path / 'Inbox'
        self.needs_action_folder = self.vault_path / 'Needs_Action'
        self.logs_folder = self.vault_path.parent / 'watchers' / 'logs'
        
        # Ensure folders exist
        for folder in [self.inbox_folder, self.needs_action_folder, self.logs_folder]:
            folder.mkdir(exist_ok=True)
        
        logger.info(f'DailyTasksScheduler initialized - Vault: {self.vault_path}')
    
    def create_daily_summary_task(self) -> Path:
        """
        Create a daily summary task in Needs_Action folder.
        
        Returns:
            Path to created task file
        """
        timestamp = datetime.now(timezone.utc).isoformat()
        today = datetime.now().strftime('%Y-%m-%d')
        
        task_filename = f"DAILY_SUMMARY_{today}.md"
        task_path = self.needs_action_folder / task_filename
        
        task_content = f"""---
source: daily_tasks_scheduler
type: daily_summary
date: {today}
created: {timestamp}
status: pending
priority: medium
---

# Daily Summary - {today}

## Tasks Completed Yesterday

<!-- Fill in tasks completed -->

## Pending Tasks

<!-- List pending tasks -->

## Today's Priorities

<!-- Set today's priorities -->

## Notes

<!-- Add any notes -->

---
*Generated by Daily Tasks Scheduler*
"""
        
        task_path.write_text(task_content)
        logger.info(f'Daily summary task created: {task_path}')
        
        return task_path
    
    def create_recurring_task(self, task_type: str, details: Dict[str, Any]) -> Path:
        """
        Create a recurring task (e.g., check emails, review approvals).
        
        Args:
            task_type: Type of recurring task
            details: Task details dictionary
            
        Returns:
            Path to created task file
        """
        timestamp = datetime.now(timezone.utc).isoformat()
        
        task_filename = f"RECURRING_{task_type.upper()}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        task_path = self.needs_action_folder / task_filename
        
        task_content = f"""---
source: daily_tasks_scheduler
type: recurring
recurring_type: {task_type}
created: {timestamp}
status: pending
priority: medium
---

# Recurring Task: {task_type.replace('_', ' ').title()}

**Schedule**: {details.get('schedule', 'Daily')}  
**Last Run**: {details.get('last_run', 'N/A')}

## Task Description

{details.get('description', 'Automated recurring task')}

## Action Items

{chr(10).join([f"- [ ] {item}" for item in details.get('actions', ['Review and complete task'])])}

## Notes

<!-- Add notes here -->

---
*Generated by Daily Tasks Scheduler*
"""
        
        task_path.write_text(task_content)
        logger.info(f'Recurring task created: {task_path}')
        
        return task_path
    
    def check_completed_tasks(self, date: str = None) -> Dict[str, Any]:
        """
        Check completed tasks for a given date.
        
        Args:
            date: Date string (YYYY-MM-DD), defaults to yesterday
            
        Returns:
            Dictionary with task statistics
        """
        if date is None:
            # Default to yesterday
            from datetime import timedelta
            yesterday = datetime.now() - timedelta(days=1)
            date = yesterday.strftime('%Y-%m-%d')
        
        done_folder = self.vault_path / 'Done'
        
        if not done_folder.exists():
            return {'count': 0, 'tasks': []}
        
        # Count tasks completed on given date
        completed_tasks = []
        for file in done_folder.glob('*.md'):
            try:
                content = file.read_text()
                # Look for completion date in frontmatter or filename
                if date in file.name or date in content[:500]:
                    completed_tasks.append(file.name)
            except Exception as e:
                logger.error(f'Error reading file {file.name}: {e}')
        
        return {
            'date': date,
            'count': len(completed_tasks),
            'tasks': completed_tasks
        }
    
    def generate_daily_report(self) -> str:
        """
        Generate a daily report of completed tasks.
        
        Returns:
            Markdown report content
        """
        stats = self.check_completed_tasks()
        
        report = f"""# Daily Report - {stats['date']}

## Summary

**Tasks Completed**: {stats['count']}

## Completed Tasks

"""
        
        if stats['tasks']:
            for task in stats['tasks']:
                report += f"- {task}\n"
        else:
            report += "*No tasks completed*\n"
        
        report += f"\n---\n*Generated by Daily Tasks Scheduler*\n"
        
        return report
    
    def log_action(self, action: str, status: str, details: Dict[str, Any] = None) -> None:
        """
        Log scheduler action to operations.log.
        
        Args:
            action: Action type
            status: Action status
            details: Additional details dictionary
        """
        log_entry = {
            'timestamp': datetime.now(timezone.utc).isoformat(),
            'action': action,
            'source': 'daily_tasks.py',
            'status': status,
            'duration_ms': 0,
            'user': 'system',
            'details': details or {}
        }
        
        log_file = self.logs_folder / 'operations.log'
        log_file.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            with open(log_file, 'a') as f:
                f.write(json.dumps(log_entry) + '\n')
            logger.info(f'Action logged: {action} ({status})')
        except Exception as e:
            logger.error(f'Error logging action: {e}')


def run_daily_tasks(vault_path: str = None) -> None:
    """
    Run daily tasks scheduler.
    
    Args:
        vault_path: Path to AI_Employee_Vault (default: auto-detect)
    """
    if vault_path is None:
        vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'
    
    scheduler = DailyTasksScheduler(str(vault_path))
    
    # Create daily summary task
    scheduler.create_daily_summary_task()
    
    # Create recurring tasks
    scheduler.create_recurring_task('email_check', {
        'schedule': 'Daily at 8 AM',
        'description': 'Check and process new emails',
        'actions': [
            'Review inbox for new emails',
            'Process urgent emails',
            'Archive processed emails'
        ]
    })
    
    scheduler.create_recurring_task('approval_review', {
        'schedule': 'Daily at 9 AM',
        'description': 'Review pending approvals',
        'actions': [
            'Check Pending_Approval folder',
            'Review each pending task',
            'Approve or reject tasks'
        ]
    })
    
    # Log action
    scheduler.log_action('daily_tasks_run', 'success', {
        'tasks_created': 3
    })
    
    logger.info('Daily tasks scheduler completed')


if __name__ == '__main__':
    print('\n=== DAILY TASKS SCHEDULER TEST ===')
    run_daily_tasks()
    print('[OK] Daily tasks created successfully')
    print('=== TEST COMPLETE ===')
