#!/usr/bin/env python3
"""
Daily Tasks - Silver Tier

Generates daily task summaries at 8 AM.
Run via cron or Task Scheduler.
"""

import logging
from pathlib import Path
from datetime import datetime, timedelta

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('daily_tasks')


def generate_daily_summary(vault_path: str):
    """
    Generate daily task summary.
    
    Args:
        vault_path: Path to AI_Employee_Vault
    """
    vault = Path(vault_path)
    needs_action = vault / 'Needs_Action'
    done = vault / 'Done'
    
    logger.info(f'Generating daily summary for {vault_path}')
    
    # Count tasks
    pending_count = len(list(needs_action.glob('*.md'))) if needs_action.exists() else 0
    completed_count = len(list(done.glob('*.md'))) if done.exists() else 0
    
    # Get today's date
    today = datetime.now().strftime('%Y-%m-%d')
    
    # Create daily summary task
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    summary_file = needs_action / f'DAILY_SUMMARY_{timestamp}.md'
    
    content = f"""---
source: daily_tasks
type: daily_summary
date: {today}
generated: {datetime.now().isoformat()}
status: pending
---

# Daily Summary - {today}

**Generated**: {datetime.now().isoformat()}

## Task Overview

| Status | Count |
|--------|-------|
| Pending | {pending_count} |
| Completed Today | {completed_count} |

## Pending Tasks

"""
    
    # List pending tasks
    if pending_count > 0:
        for i, task_file in enumerate(needs_action.glob('*.md'), 1):
            content += f"{i}. {task_file.stem}\n"
    else:
        content += "*No pending tasks*\n"
    
    content += f"""
## Completed Tasks

"""
    
    # List completed tasks
    if completed_count > 0:
        for i, task_file in enumerate(list(done.glob('*.md'))[-10:], 1):
            content += f"{i}. {task_file.stem}\n"
    else:
        content += "*No completed tasks*\n"
    
    content += f"""
## Action Items

- [ ] Review pending tasks
- [ ] Complete high-priority tasks
- [ ] Archive completed tasks
- [ ] Plan tomorrow's tasks

## Notes

<!-- Add notes here -->

---
*Generated by Daily Tasks - Silver Tier*
"""
    
    # Write summary file
    summary_file.write_text(content)
    
    logger.info(f'Daily summary generated: {summary_file.name}')
    logger.info(f'Pending: {pending_count}, Completed: {completed_count}')


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) < 2:
        print('Usage: python daily_tasks.py <vault_path>')
        sys.exit(1)
    
    vault_path = sys.argv[1]
    generate_daily_summary(vault_path)
