#!/usr/bin/env python3
"""
Weekly Summary - Silver Tier

Generates weekly task summaries at 9 AM on Mondays.
Run via cron or Task Scheduler.
"""

import logging
from pathlib import Path
from datetime import datetime, timedelta

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('weekly_summary')


def generate_weekly_summary(vault_path: str):
    """
    Generate weekly task summary.
    
    Args:
        vault_path: Path to AI_Employee_Vault
    """
    vault = Path(vault_path)
    needs_action = vault / 'Needs_Action'
    done = vault / 'Done'
    summaries = vault / 'Summaries'
    
    summaries.mkdir(exist_ok=True)
    
    logger.info(f'Generating weekly summary for {vault_path}')
    
    # Calculate last 7 days
    today = datetime.now()
    week_ago = today - timedelta(days=7)
    
    # Count tasks
    pending_count = len(list(needs_action.glob('*.md'))) if needs_action.exists() else 0
    
    # Get completed tasks from last 7 days
    completed_tasks = []
    if done.exists():
        for task_file in done.glob('*.md'):
            try:
                content = task_file.read_text()
                if 'Completed:' in content:
                    # Extract completion date
                    for line in content.split('\n'):
                        if 'Completed:' in line:
                            completed_tasks.append(task_file)
                            break
            except Exception:
                pass
    
    completed_count = len(completed_tasks)
    
    # Create weekly summary
    week_start = week_ago.strftime('%Y-%m-%d')
    week_end = today.strftime('%Y-%m-%d')
    timestamp = today.strftime('%Y%m%d_%H%M%S')
    summary_file = summaries / f'WEEKLY_SUMMARY_{timestamp}.md'
    
    content = f"""---
source: weekly_summary
type: weekly_summary
week_start: {week_start}
week_end: {week_end}
generated: {datetime.now().isoformat()}
status: pending
---

# Weekly Summary - {week_start} to {week_end}

**Generated**: {datetime.now().isoformat()}

## Week Overview

| Metric | Count |
|--------|-------|
| Pending Tasks | {pending_count} |
| Completed This Week | {completed_count} |
| Completion Rate | {(completed_count / (completed_count + pending_count) * 100) if (completed_count + pending_count) > 0 else 0:.1f}% |

## Pending Tasks

"""
    
    # List pending tasks
    if pending_count > 0:
        for i, task_file in enumerate(needs_action.glob('*.md'), 1):
            content += f"{i}. {task_file.stem}\n"
    else:
        content += "*No pending tasks*\n"
    
    content += f"""
## Completed This Week

"""
    
    # List completed tasks
    if completed_count > 0:
        for i, task_file in enumerate(completed_tasks[-15:], 1):
            content += f"{i}. {task_file.stem}\n"
    else:
        content += "*No completed tasks this week*\n"
    
    content += f"""
## Achievements

<!-- Add weekly achievements here -->

## Challenges

<!-- Add challenges faced this week -->

## Next Week's Goals

- [ ] Complete pending high-priority tasks
- [ ] Start new planned tasks
- [ ] Review and archive old tasks
- [ ] Plan next week's priorities

## Notes

<!-- Add notes here -->

---
*Generated by Weekly Summary - Silver Tier*
"""
    
    # Write summary file
    summary_file.write_text(content)
    
    # Also update Dashboard.md with weekly summary
    dashboard = vault / 'Dashboard.md'
    if dashboard.exists():
        try:
            dashboard_content = dashboard.read_text()
            
            # Add weekly summary section
            weekly_section = f"""
## Weekly Summary - {week_start} to {week_end}

- **Pending Tasks**: {pending_count}
- **Completed This Week**: {completed_count}
- **Completion Rate**: {(completed_count / (completed_count + pending_count) * 100) if (completed_count + pending_count) > 0 else 0:.1f}%

*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

"""
            
            # Insert after existing content
            if '## Weekly Summary' not in dashboard_content:
                dashboard_content += '\n' + weekly_section
                dashboard.write_text(dashboard_content)
            
            logger.info('Dashboard.md updated with weekly summary')
        
        except Exception as e:
            logger.error(f'Error updating Dashboard.md: {e}')
    
    logger.info(f'Weekly summary generated: {summary_file.name}')
    logger.info(f'Pending: {pending_count}, Completed: {completed_count}')


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) < 2:
        print('Usage: python weekly_summary.py <vault_path>')
        sys.exit(1)
    
    vault_path = sys.argv[1]
    generate_weekly_summary(vault_path)
