#!/usr/bin/env python3
"""
Plan Manager - Silver Tier

Manages Plan.md lifecycle: creation, progress tracking, and archival.
"""

import logging
from pathlib import Path
from datetime import datetime
from watchers.base_watcher import BaseWatcher

# Configure logging
logger = logging.getLogger('plan_manager')


class PlanManager(BaseWatcher):
    """
    Manages Plan.md files for task tracking.
    Extends BaseWatcher with Plan.md-specific implementation.
    """
    
    def __init__(self, vault_path: str, poll_interval: int = 30):
        """
        Initialize Plan manager.
        
        Args:
            vault_path: Path to AI_Employee_Vault
            poll_interval: Seconds between scans (default: 30)
        """
        super().__init__(vault_path, poll_interval)
        
        self.plans_folder = self.vault_path / 'Plans'
        self.plans_folder.mkdir(exist_ok=True)
        
        logger.info(f'PlanManager initialized - Plans: {self.plans_folder}')
    
    def scan(self) -> list:
        """
        Scan Needs_Action for tasks that need Plan.md files.
        
        Returns:
            List of tasks needing plans
        """
        tasks_needing_plans = []
        
        try:
            # Check Needs_Action folder for new tasks
            for task_file in self.needs_action.glob('*.md'):
                content = task_file.read_text()
                
                # Check if task needs a plan (3+ action items mentioned)
                if '- [ ]' in content:
                    action_count = content.count('- [ ]')
                    
                    if action_count >= 3:
                        # Check if Plan.md already exists
                        plan_exists = (self.plans_folder / f'PLAN_{task_file.stem}.md').exists()
                        
                        if not plan_exists:
                            tasks_needing_plans.append(task_file)
                            logger.info(f'Task needs plan: {task_file.name} ({action_count} actions)')
        
        except Exception as e:
            logger.error(f'Error scanning for tasks: {e}')
        
        return tasks_needing_plans
    
    def create_task_file(self, task_file: Path) -> Path:
        """
        Create Plan.md file for task.
        
        Args:
            task_file: Path to task file
            
        Returns:
            Path to created Plan.md file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        plan_filename = f'PLAN_{task_file.stem}_{timestamp}.md'
        plan_path = self.plans_folder / plan_filename
        
        # Read task content
        task_content = task_file.read_text()
        
        # Extract action items
        action_items = []
        for line in task_content.split('\n'):
            if '- [ ]' in line:
                action_items.append(line.strip())
        
        # Create Plan.md content
        content = f"""---
source_task: {task_file.name}
status: active
created: {datetime.now().isoformat()}
updated: {datetime.now().isoformat()}
total_steps: {len(action_items)}
completed_steps: 0
iteration: 0
---

# Plan: {task_file.stem}

**Source**: {task_file.name}  
**Created**: {datetime.now().isoformat()}  
**Status**: Active

## Action Items

"""
        
        # Add action items as checkboxes
        for i, item in enumerate(action_items, 1):
            # Clean up the item (remove markdown checkbox)
            clean_item = item.replace('- [ ]', '').strip()
            content += f"{i}. [ ] {clean_item}\n"
        
        content += f"""
## Progress

**Status**: 0/{len(action_items)} completed (0%)

## Iteration Log

<!-- Iteration history will be logged here -->

## Completion Report

<!-- Will be filled when all checkboxes are complete -->

---
*Generated by PlanManager - Silver Tier*
"""
        
        # Write Plan.md file
        plan_path.write_text(content)
        
        # Log operation
        self.log_operation('create_plan', {
            'task_file': str(task_file),
            'plan_file': str(plan_path),
            'action_items': len(action_items)
        })
        
        logger.info(f'Plan created: {plan_path.name}')
        
        return plan_path
    
    def update_plan_progress(self, plan_path: Path, completed_count: int):
        """
        Update Plan.md progress.
        
        Args:
            plan_path: Path to Plan.md file
            completed_count: Number of completed steps
        """
        try:
            content = plan_path.read_text()
            
            # Extract total steps from frontmatter
            total_steps = 0
            for line in content.split('\n'):
                if 'total_steps:' in line:
                    total_steps = int(line.split(':')[1].strip())
                    break
            
            if total_steps > 0:
                # Calculate percentage
                percentage = (completed_count / total_steps) * 100
                
                # Update frontmatter
                content = content.replace(
                    'completed_steps: 0',
                    f'completed_steps: {completed_count}'
                )
                content = content.replace(
                    f'**Status**: 0/{total_steps} completed (0%)',
                    f'**Status**: {completed_count}/{total_steps} completed ({percentage:.0f}%)'
                )
                content = content.replace(
                    'updated: ',
                    f'updated: {datetime.now().isoformat()}\n# '
                )
                
                # Write updated content
                plan_path.write_text(content)
                
                logger.info(f'Plan progress updated: {completed_count}/{total_steps} ({percentage:.0f}%)')
        
        except Exception as e:
            logger.error(f'Error updating plan progress: {e}')
    
    def archive_plan(self, plan_path: Path):
        """
        Archive completed Plan.md.
        
        Args:
            plan_path: Path to Plan.md file
        """
        try:
            content = plan_path.read_text()
            
            # Update status to archived
            content = content.replace('status: active', 'status: archived')
            content = content.replace(
                'updated: ',
                f'updated: {datetime.now().isoformat()}\n# '
            )
            
            # Write updated content
            plan_path.write_text(content)
            
            logger.info(f'Plan archived: {plan_path.name}')
        
        except Exception as e:
            logger.error(f'Error archiving plan: {e}')


if __name__ == '__main__':
    # Test Plan manager
    import sys
    
    if len(sys.argv) < 2:
        print('Usage: python plan_manager.py <vault_path>')
        sys.exit(1)
    
    vault_path = sys.argv[1]
    
    manager = PlanManager(vault_path, poll_interval=10)
    
    print(f'PlanManager starting - Plans: {manager.plans_folder}')
    print('Press Ctrl+C to stop')
    
    manager.run()
